---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install tomcat
    apt: name=tomcat update_cache= yes state=present
  - name: start tomcat
    service: name=tomcat state=started
  - name: install docker
    apt: name=docker update_cache= yes state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    apt: name=git update_cache= yes state=present
  - name: clone a repo
    git: repo=https://github.com/karmasachin/AnsibleDockerdemo.git dest=/tmp/mygitrepo1
  - name: build docker file
    command: chdir=/tmp/mygitrepo1 docker build -t myfirstimage:ansible2 .
  - name: create container
    command: docker run -itd -P myfirstimage:ansible2

