---
- hosts: webservers
  become: true
  become_user: root
  tasks:
 









  - name: clone a repo
    git: repo=https://github.com/karmasachin/AnsibleDockerdemo.git dest=/tmp/mygitrepo1
  - name: build docker file
    command: chdir=/tmp/mygitrepo1 sudo docker build -t myfirstimage:ansible2 .
  - name: create container
    command: sudo docker run -itd -P myfirstimage:ansible2

